package extended

import (
	// The following imports just register themselves --
	// these are the terminal types we aggregate in this package.
	_ "github.com/badu/term/info/a/aixterm"
	_ "github.com/badu/term/info/a/alacritty"
	_ "github.com/badu/term/info/a/ansi"
	_ "github.com/badu/term/info/b/beterm"
	_ "github.com/badu/term/info/c/cygwin"
	_ "github.com/badu/term/info/d/dtterm"
	_ "github.com/badu/term/info/e/emacs"
	_ "github.com/badu/term/info/g/gnome"
	_ "github.com/badu/term/info/h/hpterm"
	_ "github.com/badu/term/info/k/konsole"
	_ "github.com/badu/term/info/k/kterm"
	_ "github.com/badu/term/info/l/linux"
	_ "github.com/badu/term/info/p/pcansi"
	_ "github.com/badu/term/info/r/rxvt"
	_ "github.com/badu/term/info/s/screen"
	_ "github.com/badu/term/info/s/simpleterm"
	_ "github.com/badu/term/info/s/sun"
	_ "github.com/badu/term/info/t/termite"
	_ "github.com/badu/term/info/t/tmux"
	_ "github.com/badu/term/info/v/vt100"
	_ "github.com/badu/term/info/v/vt102"
	_ "github.com/badu/term/info/v/vt220"
	_ "github.com/badu/term/info/v/vt320"
	_ "github.com/badu/term/info/v/vt400"
	_ "github.com/badu/term/info/v/vt420"
	_ "github.com/badu/term/info/v/vt52"
	_ "github.com/badu/term/info/w/wy50"
	_ "github.com/badu/term/info/w/wy60"
	_ "github.com/badu/term/info/w/wy99_ansi"
	_ "github.com/badu/term/info/x/xfce"
	_ "github.com/badu/term/info/x/xterm"
	_ "github.com/badu/term/info/x/xterm_kitty"
)
